--- #YAML:1.0
name                : DBIx-Safe
version             : 1.2.5
abstract            : Safe wrapper to DBI interface
author:              
  - Greg Sabino Mullane <greg@turnstep.com>

license             : bsd
dynamic_config      : 1
distribution_type   : module

requires:
  DBI               : 1.49
  DBD::Pg           : 1.49
recommends:
  Test::Dynamic     : 1.3.1
build_requires:
  Test::Harness     : 2.03
  Test::More        : 0.61
  Module::Signature : 0.50

provides:
  DBIx::Safe:
    file            : Safe.pm
    version         : 1.2.5

resources:
  homepage          : http://bucardo.org/dbix_safe/index.html
  MailingList       : http://bucardo.org/dbix_safe/list.html
  bugtracker        : http://bucardo.org/dbix_safe/bugs.html
  repository        : https://github.com/bucardo/dbixsafe
  license           : http://bucardo.org/dbix_safe/license.html
meta-spec:
  version           : 1.3
  url               : http://module-build.sourceforge.net/META-spec-v1.3.html
generated_by        : emacs 22.1.1
